# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b7648aa9ce962d640c00c7d6a1de781dbc0a8f78d3e61feacc4bdbfafff43b37b8a36ba36f7a68d000ca6cc34b706fa465851047d0cc4b11795a72c966f3916

test:
  secret_key_base: ae5e5ce731fac827f5ccfe4449d40d79eed54471a2fd0fee22929d3f30f0ee4210e550d1ef420c2c877afbda5e107e6b3b7585da8c4c4f7f68d5b771445f04fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
